name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build --no-interaction
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: package-dist

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/dist/
          name: package-dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
